server:
  #address:     ":8000"
  #openapiPath: "/api.json"
  #swaggerPath: "/swagger"

  # 基本配置
  address: ":8000"                        # 本地监听地址。默认":80"
  httpsAddr: ":443"                       # TLS/HTTPS配置，同时需要配置证书和密钥。默认关闭
  httpsCertPath: ""                           # TLS/HTTPS证书文件本地路径，建议使用绝对路径。默认关闭
  httpsKeyPath: ""                           # TLS/HTTPS密钥文件本地路径，建议使用绝对路径。默认关闭
  readTimeout: "60s"                        # 请求读取超时时间，一般不需要配置。默认为60秒
  writeTimeout: "0"                          # 数据返回写入超时时间，一般不需要配置。默认不超时（0）
  idleTimeout: "60s"                        # 仅当Keep-Alive开启时有效，请求闲置时间。默认为60秒
  maxHeaderBytes: "10240"                      # 请求Header大小限制（Byte）。默认为10KB
  keepAlive: true                         # 是否开启Keep-Alive功能。默认true
  serverAgent: "GoFrame HTTP Server"        # 服务端Agent信息。默认为"GoFrame HTTP Server"

  # 接口文档
  openapiPath: "/api.json" # OpenAPI接口文档地址
  swaggerPath: "/swagger"  # 内置SwaggerUI展示地址

  # 静态服务配置
  indexFiles: [ "index.html","index.htm" ]   # 自动首页静态文件检索。默认为["index.html", "index.htm"]
  indexFolder: true                        # 当访问静态文件目录时，是否展示目录下的文件列表。默认关闭，那么请求将返回403
  serverRoot: "./resource/public"                   # 静态文件服务的目录根路径，配置时自动开启静态文件服务。默认关闭
  #searchPaths:         ["/home/www","/var/lib/www"] # 提供静态文件服务时额外的文件搜索路径，当根路径找不到时则按照顺序在搜索目录查找。默认关闭
  fileServerEnabled: true                        # 静态文件服务总开关。默认false

  # Cookie配置
  cookieMaxAge: "365d"             # Cookie有效期。默认为365天
  cookiePath: "/"                # Cookie有效路径。默认为"/"表示全站所有路径下有效
  cookieDomain: ""                 # Cookie有效域名。默认为当前配置Cookie时的域名

  # Sessions配置
  sessionMaxAge: "24h"              # Session有效期。默认为24小时
  sessionIdName: "gfsessionid"      # SessionId的键名名称。默认为gfsessionid
  sessionCookieOutput: true               # Session特性开启时，是否将SessionId返回到Cookie中。默认true
  sessionPath: "./resource/gsessions"   # Session存储的文件目录路径。默认为当前系统临时目录下的gsessions目录

  # 日志基本配置
  logPath: ""                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout: true               # 日志是否输出到终端。默认为true
  errorStack: true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  errorLogEnabled: true               # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern: "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: false              # 是否记录访问日志。默认为false
  accessLogPattern: "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

  # 日志扩展配置(参数日志组件配置)
  logger:
    path: "/var/log/"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
    prefix: ""            # 日志内容输出前缀。默认为空
    level: "all"         # 日志输出级别
    stdout: true          # 日志是否同时输出到终端。默认true
    rotateSize: 0             # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateExpire: 0             # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit: 0             # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire: 0             # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupCompress: 0             # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
    rotateCheckInterval: "1h"          # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时

    # PProf配置
    pprofEnabled: false              # 是否开启PProf性能调试特性。默认为false
    pprofPattern: ""                 # 开启PProf时有效，表示PProf特性的页面访问路径，对当前Server绑定的所有域名有效。

    # 其他配置
    clientMaxBodySize: 810241024          # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB
    formParsingMemory: 1048576            # 解析表单时的缓冲区大小(Byte)，一般不需要配置。默认为1024*1024=1MB
    nameToUriType: 0                  # 路由注册中使用对象注册时的路由生成规则。默认为0
    routeOverWrite: false              # 当遇到重复路由注册时是否强制覆盖。默认为false，重复路由存在时将会在启动时报错退出
    dumpRouterMap: true               # 是否在Server启动时打印所有的路由列表。默认为true
    graceful: false              # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false
    gracefulTimeout: 2                  # 父进程在平滑重启后多少秒退出，默认2秒。若请求耗时大于该值，可能会导致请求中断

# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  sys:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  account:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  pay:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  store:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  pt:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  order:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  shop:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  admin:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  cms:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  marketing:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  trade:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  invoicing:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  sns:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

  o2o:
    link: "mysql:modulith_open:pwd@tcp(localhost:3306)/modulith_open?loc=Local&parseTime=true"
    debug: true

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db: 10
    pass: dev_pwd_123

    minIdle: "4"   # 允许闲置的最小连接数
    maxIdle: "8"  # 允许闲置的最大连接数(0表示不限制)
    maxActive: "16" # 最大连接数量限制(0表示不限制)
    idleTimeout: "30m"  # 连接最大空闲时间，使用时间字符串例如30s/1m/1d

  # 单实例配置示例2
  cache:
    address: 127.0.0.1:6379
    db: 10
    pass: dev_pwd_123

    minIdle: "4"   # 允许闲置的最小连接数
    maxIdle: "8"  # 允许闲置的最大连接数(0表示不限制)
    maxActive: "16" # 最大连接数量限制(0表示不限制)
    idleTimeout: "30m"  # 连接最大空闲时间，使用时间字符串例如30s/1m/1d

logger:
  level: "all"
  stdout: true

jwt:
  # 认证信息Http请求头
  tokenHeader: "Authorization"

  # 认证信息Http请求头
  tokenPrefix: "Bearer "

  # token secret
  tokenSecret: "43286a86708820e38c333cdd4c496355"

  # 过期时间 单位minutes
  tokenTttl: 3600

  # 刷新时间 单位minutes
  tokenRefreshTtl: 20160


secure:
  publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBT2vr+dhZElF73FJ6xiP181txKWUSNLPQQlid6DUJhGAOZblluafIdLmnUyKE8mMHhT3R+Ib3ssZcJku6Hn72yHYj/qPkCGFv0eFo7G+GJfDIUeDyalBN0QsuiE/XzPHJBuJDfRArOiWvH0BXOv5kpeXSXM8yTt5Na1jAYSiQ/wIDAQAB"
  privateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMFPa+v52FkSUXvcUnrGI/XzW3EpZRI0s9BCWJ3oNQmEYA5luWW5p8h0uadTIoTyYweFPdH4hveyxlwmS7oefvbIdiP+o+QIYW/R4Wjsb4Yl8MhR4PJqUE3RCy6IT9fM8ckG4kN9ECs6Ja8fQFc6/mSl5dJczzJO3k1rWMBhKJD/AgMBAAECgYEAucMakH9dWeryhrYoRHcXo4giPVJsH9ypVt4KzmOQY/7jV7KFQK3x//27UoHfUCak51sxFw9ek7UmTPM4HjikA9LkYeE7S381b4QRvFuf3L6IbMP3ywJnJ8pPr2l5SqQ00W+oKv+w/VmEsyUHr+k4Z+4ik+FheTkVWp566WbqFsECQQDjYaMcaKw3j2Zecl8T6eUe7fdaRMIzp/gcpPMfT/9rDzIQk+7ORvm1NI9AUmFv/FAlfpuAMrdL2n7p9uznWb7RAkEA2aP934kbXg5bdV0R313MrL+7WTK/qdcYxATUbMsMuWWQBoS5irrt80WCZbG48hpocJavLNjbtrjmUX3CuJBmzwJAOJg8uP10n/+ZQzjEYXh+BszEHDuw+pp8LuT/fnOy5zrJA0dO0RjpXijO3vuiNPVgHXT9z1LQPJkNrb5ACPVVgQJBALPeb4uV0bNrJDUb5RB4ghZnIxv18CcaqNIft7vuGCcFBAIPIRTBprR+RuVq+xHDt3sNXdsvom4h49+Hky1b0ksCQBBwUtVaqH6ztCtwUF1j2c/Zcrt5P/uN7IHAd44K0gIJc1+Csr3qPG+G2yoqRM8KVqLI8Z2ZYn9c+AvEE+L9OQY="

  ignore: #配置白名单路径
    - "/swagger/"
    - "/api.json"
    - "/front/sys/config/listTranslateLang"
    - "/front/account/user/info"
    - "/front/sys/captcha/index"
    - "/front/sys/config/info"
    - "/front/sys/config/publicKey"
    - "/front/sys/upload/index"
    - "/front/account/login/login"
    - "/front/account/login/register"
    - "/front/sys/district/tree"
    - "/front/pay/callback/wechatNotify"
    - "/front/pay/callback/alipayNotify"
    - "/front/pay/callback/alipayReturn"
    - "/front/pay/callback/returnUrl"


    - "/front/sys/page/getMobilePage"
    - "/front/sys/page/getPcPage"
    - "/front/sys/page/pcLayout"
    - "/front/pt/product/listCategory"
    - "/front/pt/product/treeCategory"
    - "/front/pt/product/list"
    - "/front/pt/product/listItem"
    - "/front/pt/product/detail"

    - "/front/marketing/activityBase/listVoucher"

    - "/front/shop/mobile/getSearchInfo"
    - "/front/pt/product/getSearchFilter"



# 系统配置
shopSuite:
  # 版本号
  version: "v1.0.0"

  # 调试模式
  appDebug: "true"

  # 调试模式
  dbDebug: "true"

  # 文件上传磁盘位置
  uploadDir: "./resource/public/uploads"

  urlBase: "http://127.0.0.1:8000"
  urlH5: "http://localhost:8080/#"
  urlPc: "https://demo.modulithshop.cn"

  # 启用缓存
  cacheEnable: "false"

  cacheNamespace: "c:1001:"



