# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:3306)/modulith_open?loc=Local&parseTime=true"
        group: "merchant"
        removePrefix: "merchant_"
        tables: "merchant_base"
        jsonCase: "Snake"
        gJsonSupport: true
        overwriteDao: true


