// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"golershop.cn/internal/dao/internal"
)

// baseDao is the data access object for the table merchant_base.
// You can define custom methods on it to extend its functionality as needed.
type baseDao struct {
	*internal.BaseDao
}

var (
	// Base is a globally accessible object for table merchant_base operations.
	MerchantBase = baseDao{internal.NewBaseDao()}
)

// Add your custom methods and functionality below.
